import { ThemeProvider } from 'components/react-bricks/theme-provider';
import '../../globals.css';
import ReactBricksApp from './react-bricks-app';

export const metadata = {
  title: 'React Bricks Admin',
  description: 'Generated by Next.js'
};

export default function AdminLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`dark:bg-gray-900`}>
        <ThemeProvider
          attribute="class"
          storageKey="color-mode"
          defaultTheme="system"
          enableSystem={true}
        >
          <main>
            <ReactBricksApp>{children}</ReactBricksApp>
          </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
